import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // "Sapphire & Ink" — keep in sync with app/globals.css @theme.
        "primary": "#1f43b8",
        "primary-container": "#2b52d4",
        "primary-fixed": "#dde4ff",
        "primary-fixed-dim": "#a8bbf0",
        "inverse-primary": "#a8bbf0",
        "surface-tint": "#1f43b8",
        "on-primary": "#ffffff",
        "on-primary-container": "#eaefff",
        "on-primary-fixed": "#001449",
        "on-primary-fixed-variant": "#15368f",
        "background": "#fcfcfd",
        "surface": "#fcfcfd",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f7f9",
        "surface-container": "#f0f1f4",
        "surface-container-high": "#e8eaee",
        "surface-container-highest": "#e1e3e9",
        "surface-dim": "#e5e6eb",
        "surface-variant": "#e8eaee",
        "on-background": "#17181d",
        "on-surface": "#17181d",
        "on-surface-variant": "#5b5e6b",
        "outline": "#888b96",
        "outline-variant": "#cccfd8",
        "inverse-surface": "#1e2028",
        "inverse-on-surface": "#f3f3f6",
        "secondary": "#4a5064",
        "secondary-container": "#eaecf3",
        "secondary-fixed": "#e5e7f0",
        "secondary-fixed-dim": "#c3c7d6",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#363b4c",
        "on-secondary-fixed": "#1a1f2e",
        "on-secondary-fixed-variant": "#383e51",
        "tertiary": "#9a5a1e",
        "tertiary-container": "#a35c17",
        "tertiary-fixed": "#ffe1c6",
        "tertiary-fixed-dim": "#f0bd8b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fff3e9",
        "on-tertiary-fixed": "#391c00",
        "on-tertiary-fixed-variant": "#7a4310",
        "error": "#c62f1e",
        "error-container": "#fbe3df",
        "on-error": "#ffffff",
        "on-error-container": "#7a1a0d",
        "success-accent": "#1f43b8",
        "success": "#1f7a45",
        "success-container": "#ddf1e5",
        "on-success": "#ffffff",
        "on-success-container": "#093521",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        gutter: "24px",
        // xl/xxl tightened from 48/80 — keep in sync with app/globals.css.
        xl: "32px",
        sm: "8px",
        md: "16px",
        xxl: "48px",
        xs: "4px",
        // Gap between stacked page sections (outer `flex flex-col`).
        section: "42px",
        "sidebar-width": "280px",
      },
      fontFamily: {
        "label-caps": ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["32px", { lineHeight: "1.25", fontWeight: "600", letterSpacing: "-0.01em" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600", letterSpacing: "-0.01em" }],
        "body-lg": ["18px", { lineHeight: "1.555556", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.428571", fontWeight: "500", letterSpacing: "0.01em" }],
        "label-sm": ["12px", { lineHeight: "1.333333", fontWeight: "500", letterSpacing: "0.01em" }],
        "caption": ["11px", { lineHeight: "1.454545", fontWeight: "500", letterSpacing: "0.01em" }],
        "label-caps": ["12px", { lineHeight: "1", fontWeight: "500", letterSpacing: "0.05em" }],
      },
    },
  },
  plugins: [],
};
export default config;
