import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#1e56a0",
        "surface-container": "#d6e4f0",
        "tertiary-container": "#d3e2f0",
        "tertiary-fixed": "#d6e4f0",
        "background": "#f6f6f6",
        "primary-container": "#163172",
        "surface-container-high": "#c3d7ea",
        "inverse-on-surface": "#eef3f9",
        "tertiary-fixed-dim": "#9fbfe0",
        "inverse-primary": "#9fbfe0",
        "on-tertiary-container": "#0f234f",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#9fbfe0",
        "secondary": "#163172",
        "on-primary-fixed": "#163172",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-dim": "#c9d9ea",
        "on-primary-fixed-variant": "#163172",
        "on-background": "#163172",
        "error-container": "#ffdad6",
        "on-surface-variant": "#4c6690",
        "surface-tint": "#1e56a0",
        "outline-variant": "#c9d9ea",
        "surface-container-low": "#eef3f9",
        "secondary-fixed-dim": "#4c5f82",
        "surface-bright": "#f6f6f6",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#163172",
        "secondary-container": "#1c3f74",
        "on-primary": "#ffffff",
        "surface-container-highest": "#aec8e0",
        "on-surface": "#163172",
        "on-primary-container": "#d6e4f0",
        "primary-fixed": "#d6e4f0",
        "surface": "#f6f6f6",
        "on-tertiary-fixed-variant": "#163172",
        "on-secondary-fixed-variant": "#24467e",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#1c3f74",
        "surface-variant": "#d3e2f0",
        "outline": "#7391b8",
        "success-accent": "#1e56a0",
        "tertiary": "#163172",
        "on-secondary-container": "#d6e4f0",
        "secondary-fixed": "#ced9ee",
        "on-secondary-fixed": "#163172",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        gutter: "24px",
        xl: "32px",
        sm: "8px",
        md: "16px",
        xxl: "48px",
        xs: "4px",
        "sidebar-width": "280px",
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "1.2", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", fontWeight: "600", letterSpacing: "0.05em" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "caption": ["10px", { lineHeight: "1.2", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
