import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0058c9",
        "surface-container": "#ebedfb",
        "tertiary-container": "#e8ddff",
        "tertiary-fixed": "#e8ddff",
        "background": "#faf8ff",
        "primary-container": "#00429a",
        "surface-container-high": "#e5e7f5",
        "inverse-on-surface": "#eef0fd",
        "tertiary-fixed-dim": "#cebef7",
        "inverse-primary": "#b0c6ff",
        "on-tertiary-container": "#4b3f6f",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b0c6ff",
        "secondary": "#5a5c7e",
        "on-primary-fixed": "#001944",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-dim": "#d7d9e6",
        "on-primary-fixed-variant": "#00429a",
        "on-background": "#181b25",
        "error-container": "#ffdad6",
        "on-surface-variant": "#424654",
        "surface-tint": "#0058c9",
        "outline-variant": "#c2c6d6",
        "surface-container-low": "#f2f3ff",
        "secondary-fixed-dim": "#c3c3eb",
        "surface-bright": "#faf8ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#1f1341",
        "secondary-container": "#e0e0ff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e0e2ef",
        "on-surface": "#181b25",
        "on-primary-container": "#b0c6ff",
        "primary-fixed": "#d9e2ff",
        "surface": "#faf8ff",
        "on-tertiary-fixed-variant": "#4b3f6f",
        "on-secondary-fixed-variant": "#424465",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d303a",
        "surface-variant": "#dee2f2",
        "outline": "#727785",
        "success-accent": "#0058c9",
        "tertiary": "#645788",
        "on-secondary-container": "#424465",
        "secondary-fixed": "#e0e0ff",
        "on-secondary-fixed": "#171937",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        gutter: "24px",
        xl: "32px",
        sm: "8px",
        md: "16px",
        xxl: "48px",
        xs: "4px",
        "sidebar-width": "280px",
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "1.2", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", fontWeight: "600", letterSpacing: "0.05em" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "caption": ["10px", { lineHeight: "1.2", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
