"""Cost-reduction changes to the tailoring pipeline:
  - Agent 3 (bullet rewriter) now runs on the premium model tier
  - prep questions are NOT generated by run_tailoring_pipeline anymore
    (they're lazy — see routers/ai.py GET /ai/sessions/{id}/questions)
"""
import pytest
from unittest.mock import AsyncMock, MagicMock

from app.services.tailoring import (
    _agent3_write, run_tailoring_pipeline, TailoringResult,
    MappingPlan, BulletMapping, WriterOutput, RewrittenBullet,
    JDAnalysis, SemanticMatchResult, GapFillerOutput, InterviewQuestionsWrapper,
)


def _jd_analysis(**over):
    base = dict(
        exact_technical_tools=["Python"], methodologies_and_frameworks=[],
        domain_expertise_themes=[], seniority_indicators=[], ats_filter_phrases=[],
        core_responsibilities=[], target_job_titles=[], nice_to_have_skills=[], importance={},
    )
    base.update(over)
    return JDAnalysis(**base)


@pytest.mark.asyncio
async def test_agent3_write_requests_premium_tier():
    provider = MagicMock()
    provider.complete_structured = AsyncMock(
        return_value=WriterOutput(rewritten_bullets=[], updated_skills=[])
    )
    plan = MappingPlan(
        mapping_plan=[BulletMapping(
            original_bullet_id="exp0_b0", original_text="Used Python",
            target_jd_keywords_to_inject=["Python"], preserved_metrics=[],
            strategic_instruction="REINFORCE",
        )],
        plausible_skills_to_add=[],
    )
    await _agent3_write(plan, ["Python"], 50, provider)
    assert provider.complete_structured.call_args.kwargs["model_tier"] == "premium"


@pytest.mark.asyncio
async def test_run_tailoring_pipeline_does_not_generate_prep_questions():
    seen_schemas = []

    async def fake_structured(system, user, schema, **kw):
        seen_schemas.append(schema)
        return {
            "_JDAnalysisWire": _jd_analysis(exact_technical_tools=["Python"]),
            "MappingPlan": MappingPlan(
                mapping_plan=[BulletMapping(
                    original_bullet_id="exp0_b0", original_text="Used Python",
                    target_jd_keywords_to_inject=["Python"], preserved_metrics=[],
                    strategic_instruction="REINFORCE",
                )],
                plausible_skills_to_add=[],
            ),
            "WriterOutput": WriterOutput(
                rewritten_bullets=[RewrittenBullet(bullet_id="exp0_b0", rewritten_text="Built with Python")],
                updated_skills=["Python"],
            ),
            "SemanticMatchResult": SemanticMatchResult(verdicts=[]),
            "GapFillerOutput": GapFillerOutput(bullets=[], headline=""),
        }[schema.__name__]

    provider = MagicMock()
    provider.complete_structured = AsyncMock(side_effect=fake_structured)

    resume = {"experience": [{"title": "Eng", "bullets": ["Used Python"]}], "skills": ["Python"]}
    result = await run_tailoring_pipeline(resume, "Need Python.", 50, provider, MagicMock())

    assert isinstance(result, TailoringResult)
    assert result.prep_questions == []
    assert InterviewQuestionsWrapper not in seen_schemas
