import Link from "next/link";
import { RocketLaunch } from "@phosphor-icons/react/dist/ssr";

// TEMPLATE — replace [Legal Entity Name], [Contact Email], and [Jurisdiction]
// with real values, and have this reviewed by a lawyer before relying on it
// for a public launch. It is not legal advice.
const LAST_UPDATED = "August 8, 2026";

export const metadata = { title: "Terms of Service — Career Copilot" };

export default function TermsOfServicePage() {
  return (
    <div className="relative z-[1] min-h-screen flex flex-col">
      <nav className="flex items-center justify-between px-gutter py-lg max-w-[1440px] mx-auto w-full">
        <Link href="/" className="flex items-center gap-md">
          <div className="w-9 h-9 rounded-full bg-primary flex items-center justify-center">
            <RocketLaunch size={18} weight="fill" className="text-on-primary" />
          </div>
          <span className="text-headline-md font-black text-on-background tracking-tight">Career Copilot</span>
        </Link>
        <Link href="/" className="text-label-md text-on-surface-variant hover:text-on-surface transition-colors">
          Back to home
        </Link>
      </nav>

      <main className="flex-1 px-gutter py-xxl">
        <article className="max-w-[720px] mx-auto flex flex-col gap-lg">
          <div>
            <h1 className="text-headline-xl text-on-surface mb-sm">Terms of Service</h1>
            <p className="text-body-sm text-on-surface-variant">Last updated: {LAST_UPDATED}</p>
          </div>

          <p className="text-body-md text-on-surface-variant">
            By creating an account or using Career Copilot (&quot;the Service&quot;), you agree to these
            terms. If you do not agree, do not use the Service.
          </p>

          <section className="flex flex-col gap-sm">
            <h2 className="text-headline-md text-on-surface font-semibold">The Service</h2>
            <p className="text-body-md text-on-surface-variant">
              Career Copilot provides AI-assisted resume building, job-description analysis, ATS scoring,
              and interview preparation. Outputs are generated by third-party AI models and are provided
              for informational purposes — you are responsible for reviewing and verifying all generated
              content (including resume text and ATS scores) before relying on or submitting it.
            </p>
          </section>

          <section className="flex flex-col gap-sm">
            <h2 className="text-headline-md text-on-surface font-semibold">Your account</h2>
            <p className="text-body-md text-on-surface-variant">
              You&apos;re responsible for keeping your login credentials secure and for all activity under
              your account. You must provide accurate information and are responsible for the content you
              upload or generate.
            </p>
          </section>

          <section className="flex flex-col gap-sm">
            <h2 className="text-headline-md text-on-surface font-semibold">Acceptable use</h2>
            <p className="text-body-md text-on-surface-variant">
              Don&apos;t use the Service to upload content you don&apos;t have the right to share, to
              attempt to disrupt or reverse-engineer the Service, or to generate content for unlawful
              purposes.
            </p>
          </section>

          <section className="flex flex-col gap-sm">
            <h2 className="text-headline-md text-on-surface font-semibold">No warranty</h2>
            <p className="text-body-md text-on-surface-variant">
              The Service, including AI-generated content, is provided &quot;as is&quot; without warranties
              of any kind. AI-generated resume content, ATS scores, and interview questions may be
              inaccurate or incomplete — they do not guarantee interview or job outcomes.
            </p>
          </section>

          <section className="flex flex-col gap-sm">
            <h2 className="text-headline-md text-on-surface font-semibold">Limitation of liability</h2>
            <p className="text-body-md text-on-surface-variant">
              To the fullest extent permitted by law, [Legal Entity Name] is not liable for indirect,
              incidental, or consequential damages arising from your use of the Service.
            </p>
          </section>

          <section className="flex flex-col gap-sm">
            <h2 className="text-headline-md text-on-surface font-semibold">Changes</h2>
            <p className="text-body-md text-on-surface-variant">
              We may update these terms from time to time. Continued use of the Service after changes take
              effect means you accept the updated terms.
            </p>
          </section>

          <section className="flex flex-col gap-sm">
            <h2 className="text-headline-md text-on-surface font-semibold">Contact</h2>
            <p className="text-body-md text-on-surface-variant">
              Questions about these terms: <a href="mailto:[Contact Email]" className="text-primary hover:underline">[Contact Email]</a>.
              Governed by the laws of [Jurisdiction].
            </p>
          </section>
        </article>
      </main>
    </div>
  );
}
